channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.1
- pip:
  - mlflow==2.21.2
  - cloudpickle==3.1.1
  - numpy==2.2.3
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - xgboost-cpu==3.0.0
name: mlflow-env
